[package]
name = "bench"
version = "0.0.0"
edition = "2024"
publish = false

[features]
small = ["fpfmt/small"]

[dependencies]
fpfmt = { path = "../.." }
ryu = "1"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "format"
harness = false
